CREATE TABLE Student (
     id INT NOT NULL AUTO_INCREMENT,
     firstname VARCHAR(128) NOT NULL,
     lastname VARCHAR(128) NOT NULL,
     user_id VARCHAR(128) NOT NULL UNIQUE,
     PRIMARY KEY (id)
);
